"""Chat — the user-facing chat surface (Q3, Q5, Q6).

Public API:
  * :mod:`harness.chat.threads`  — Pydantic models + CRUD for
    ``chat_threads`` and ``chat_messages``.
  * :mod:`harness.chat.service`  — business logic (auto-title,
    auto-create on submit_job, event hooks).
  * :mod:`harness.chat.sse`      — SSE generator. [Q6]
"""
from __future__ import annotations

from .service import (
    ChatEventSink,
    HIGH_SIGNAL_EVENT_TYPES,
    auto_create_thread_for_run,
    build_chat_context,
    post_assistant_message,
    post_system_message,
    post_tool_result,
    post_user_message,
    register_chat_event_sink,
)
from .sse import (
    DEFAULT_MAX_RUN_SECONDS,
    EVENT_CONNECTED,
    EVENT_ERROR,
    EVENT_MESSAGE_END,
    EVENT_MESSAGE_START,
    EVENT_RUN_CANCELLED,
    EVENT_RUN_COMPLETED,
    EVENT_RUN_STARTED,
    EVENT_TOKEN,
    EVENT_TOOL_COMPLETED,
    EVENT_TOOL_STARTED,
    StreamChatResponse,
    replay_thread_messages,
    stream_chat_response,
)
from .threads import (
    AUTO_TITLE_MAX_CHARS,
    DEFAULT_THREAD_TITLE,
    FINISH_REASONS,
    MESSAGE_ROLES,
    THREAD_SOURCES,
    ChatMessage,
    ChatThread,
    append_message,
    archive_thread,
    count_messages,
    count_threads,
    create_thread,
    delete_thread,
    get_message,
    get_messages,
    get_thread,
    get_thread_by_run_id,
    get_thread_by_session_id,
    list_threads,
    new_message_id,
    new_thread_id,
    set_thread_pinned,
    unarchive_thread,
    update_thread_title,
)

__all__ = [
    "AUTO_TITLE_MAX_CHARS",
    "ChatEventSink",
    "ChatMessage",
    "ChatThread",
    "DEFAULT_MAX_RUN_SECONDS",
    "DEFAULT_THREAD_TITLE",
    "EVENT_CONNECTED",
    "EVENT_ERROR",
    "EVENT_MESSAGE_END",
    "EVENT_MESSAGE_START",
    "EVENT_RUN_CANCELLED",
    "EVENT_RUN_COMPLETED",
    "EVENT_RUN_STARTED",
    "EVENT_TOKEN",
    "EVENT_TOOL_COMPLETED",
    "EVENT_TOOL_STARTED",
    "FINISH_REASONS",
    "HIGH_SIGNAL_EVENT_TYPES",
    "MESSAGE_ROLES",
    "StreamChatResponse",
    "THREAD_SOURCES",
    "append_message",
    "archive_thread",
    "auto_create_thread_for_run",
    "build_chat_context",
    "count_messages",
    "count_threads",
    "create_thread",
    "delete_thread",
    "get_message",
    "get_messages",
    "get_thread",
    "get_thread_by_run_id",
    "get_thread_by_session_id",
    "list_threads",
    "new_message_id",
    "new_thread_id",
    "post_assistant_message",
    "post_system_message",
    "post_tool_result",
    "post_user_message",
    "register_chat_event_sink",
    "replay_thread_messages",
    "set_thread_pinned",
    "stream_chat_response",
    "unarchive_thread",
    "update_thread_title",
]
