"""Daily Test Digest — scheduled summary of test results sent to configured channels."""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Any

logger = logging.getLogger(__name__)


async def generate_digest(db: Any) -> str:
    """Generate a markdown summary of the last 24h of test activity."""
    now = datetime.now(timezone.utc)
    since = now - timedelta(hours=24)

    # Pipeline runs in last 24h
    runs = await db.fetch(
        "SELECT COUNT(*) as total, "
        "SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as passed, "
        "SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) as failed "
        "FROM pipeline_runs WHERE created_at >= $1",
        since,
    )
    total_runs = runs[0]["total"] if runs else 0
    passed_runs = runs[0]["passed"] if runs else 0
    failed_runs = runs[0]["failed"] if runs else 0

    # Test results in last 24h
    tests = await db.fetch(
        "SELECT COUNT(*) as total, "
        "SUM(CASE WHEN status = 'passed' THEN 1 ELSE 0 END) as passed, "
        "SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) as failed "
        "FROM test_results WHERE created_at >= $1",
        since,
    )
    total_tests = tests[0]["total"] if tests else 0
    passed_tests = tests[0]["passed"] if tests else 0
    failed_tests = tests[0]["failed"] if tests else 0

    # PR activity
    prs = await db.fetch(
        "SELECT COUNT(*) as total FROM pr_tracker WHERE updated_at >= $1",
        since,
    )
    active_prs = prs[0]["total"] if prs else 0

    # Failed tests detail
    failures = await db.fetch(
        "SELECT test_name, error FROM test_results "
        "WHERE status = 'failed' AND created_at >= $1 "
        "ORDER BY created_at DESC LIMIT 10",
        since,
    )

    lines = ["## TestAI Daily Digest", ""]
    lines.append(f"**Period:** {since.strftime('%b %d, %H:%M')} — {now.strftime('%b %d, %H:%M')} UTC")
    lines.append("")

    # Summary
    pass_rate = round(passed_tests / max(total_tests, 1) * 100, 1)
    lines.append("### Summary")
    lines.append(f"| Metric | Value |")
    lines.append(f"|---|---|")
    status = "PASS" if failed_runs == 0 else "FAIL"
    lines.append(f"| Pipeline Runs | {total_runs} ({status} {passed_runs} passed, {failed_runs} failed) |")
    lines.append(f"| Tests Executed | {total_tests} ({pass_rate}% pass rate) |")
    lines.append(f"| Active PRs | {active_prs} |")
    lines.append("")

    # Failures
    if failures:
        lines.append("### Recent Failures")
        for f in failures:
            name = f["test_name"][:80]
            err = (f.get("error") or "")[:100]
            lines.append(f"- `{name}` — _{err}_")
        lines.append("")

    # Coverage
    try:
        cov = await db.fetchrow(
            "SELECT AVG(line_coverage) as avg_cov FROM coverage_reports WHERE created_at >= $1",
            since,
        )
        if cov and cov["avg_cov"]:
            lines.append(f"**Average Coverage:** {round(cov['avg_cov'], 1)}%")
            lines.append("")
    except Exception:
        pass

    lines.append("---")
    lines.append(f"_Generated by TestAI at {now.strftime('%Y-%m-%d %H:%M:%S UTC')}_")

    return "\n".join(lines)


async def run_digest_for_configs(db: Any, delivery_router: Any) -> None:
    """Run digest for all enabled digest configs and send via delivery router."""
    rows = await db.fetch("SELECT * FROM digest_configs WHERE enabled = true")
    if not rows:
        logger.debug("Daily digest: no enabled configs found")
        return

    content = await generate_digest(db)

    from harness.delivery.adapters.base import DeliveryTarget

    for cfg in rows:
        target = DeliveryTarget(
            platform=cfg["platform"],
            chat_id=cfg["channel_id"],
        )
        try:
            await delivery_router.deliver(content, [target], job_name="Daily Test Digest")
            logger.info("Daily digest sent to %s:%s", cfg["platform"], cfg["channel_id"])
        except Exception as e:
            logger.warning("Daily digest delivery failed for %s: %s", cfg["platform"], e)
